version: "3.8"

services:
  minecraft-hybrid:
    image: itzg/minecraft-server:java21
    container_name: EyedComun-Pruebas
    restart: unless-stopped
    tty: true
    stdin_open: true
    stop_signal: SIGTERM

    ports:
      - "25565:25565"
      - "25575:25575"
      - "24454:24454/udp"

    environment:
      EULA: "TRUE"
      TYPE: "ARCLIGHT"
      VERSION: "1.21.1"

      SKIP_DOWNLOAD_CONTENT_CHECK: "TRUE"
      FORCE_REDOWNLOAD: "FALSE"
      DOWNLOAD_MAX_ATTEMPTS: "1"

      MEMORY: "8G"
      INIT_MEMORY: "8G"
      MAX_MEMORY: "8G"

      JVM_XX_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=35 -XX:G1MaxNewSizePercent=45 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
      JVM_OPTS: "-Dusing.aikars.flags=https://mcutils.com -Daikars.new.flags=true"

      PUID: 1000
      PGID: 100
      MOTD: "§d§lEyedComun §f| §5NEOFORGE + PLUGINS"
      ONLINE_MODE: "TRUE"

      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_PORT: "25575"

    volumes:
      - /minecraftpruebas/data:/data

    # Opcional fuera de Swarm. Si Portainer ignora deploy, usa estas en su lugar.
    mem_limit: 9500m
    mem_reservation: 8g
    cpus: "1.5"
